[package]
name = "giants-core-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
log = "0.4.27"
once_cell = "1.21.3"
reqwest = "0.12.15"
scraper = "0.23.1"
struct_iterable = "0.1.1"
